name: SilentEye CI/CD

on:
  push:
    branches:
      - dev  # Specify the branch from where you want to run when data will be pushed to this branch

jobs:
  build:

    runs-on: self-hosted

    steps:
      - name: Adjust Permissions
        run: |
          sudo chown -R $USER:$USER /var/www/html/actions-runner/_work/SilentEye-Admin-Backend/SilentEye-Admin-Backend
          sudo chmod -R 755 /var/www/html/actions-runner/_work/SilentEye-Admin-Backend/SilentEye-Admin-Backend

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'  # Adjust the Node.js version as per your requirement

      - name: Install Dependencies
        run: npm ci

      - name: Set Node.js Permissions
        run: |
          sudo chown root:root /root/.nvm/versions/node/v16.20.2/bin/node
          sudo chmod +x /root/.nvm/versions/node/v16.20.2/bin/node

      - name: Set Environment Variables
        run: |
          echo "${{ secrets.PORT }}" >> .env
          echo "${{ secrets.MONGO_URI }}" >> .env
          echo "${{ secrets.SALT_ROUNDS }}" >> .env
          echo "${{ secrets.ACCESS_TOKEN_SECRET }}" >> .env
          echo "${{ secrets.ACCESS_TOKEN_EXPIRY_TIME }}" >> .env
          echo "${{ secrets.REFRESH_TOKEN_SECRET }}" >> .env
          echo "${{ secrets.REFRESH_TOKEN_EXPIRY_TIME }}" >> .env
          echo "${{ secrets.FRONTEND_URL }}" >> .env

      # - name: Start Node.js Application
      #   run: npm start
